dictknife/cli.py, dictknife/commandline.py, dictknife/commands/dictknife.py, dictknife/commands/jsonknife.py, dictknife/commands/swaggerknife.py, dictknife/langhelpers.py, examples/optimize/Makefile, setup.py
=> Drop click

dictknife/commands/dictknife.py, dictknife/loading/__init__.py, dictknife/loading/_gsuite.py, dictknife/loading/_lazyimport.py, dictknife/loading/csv.py, dictknife/loading/spreadsheet.py, dictknife/tests/loading/test_spreadsheet.py, examples/loading/optional/00sheet.py, examples/loading/optional/Makefile, examples/loading/optional/dst/00.json, examples/loading/optional/dst/01.json, examples/loading/optional/dst/02.json, setup.py
#42 
```console
$ dictknife cat -i spreadsheet '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms#/Class Data!A1:E' -o json
$ dictknife cat -i spreadsheet 'https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/edit#gid=0' -o json 
```
=> Spreadsheet

dictknife/diff.py, dictknife/tests/test_diff.py
=> Fix dict rows

Makefile, dictknife/jsonknife/resolver.py, examples/jsonknife/bundle/00bundle.py, examples/jsonknife/bundle/01with-version.py, examples/jsonknife/bundle/02xref.py, examples/jsonknife/bundle/Makefile, examples/jsonknife/bundle/dst/00.yaml, examples/jsonknife/bundle/dst/01.yaml, examples/jsonknife/bundle/dst/02.yaml, examples/jsonknife/bundle/src/data.yaml, examples/jsonknife/bundle/src/doc.yaml, examples/jsonknife/bundle/src/main.yaml
=> Prevent infinite recursion

dictknife/cliutils/extraarguments.py, dictknife/commands/swaggerknife.py, dictknife/jsonknife/relpath.py, dictknife/langhelpers.py, dictknife/transform.py, examples/swaggerknife/merge/dst/00ref.json
=> Fix sw merge

Makefile, dictknife/commands/jsonknife.py, dictknife/jsonknife/__init__.py, dictknife/jsonknife/bundler.py, dictknife/jsonknife/resolver.py, examples/jsonknife/bundle/Makefile, examples/jsonknife/bundle/dst/03.yaml, examples/jsonknife/bundle/dst/04.yaml, examples/jsonknife/bundle/dst/05.yaml, examples/jsonknife/bundle/dst/06.yaml, examples/jsonknife/bundle/dst/07.yaml, examples/jsonknife/bundle/src/01/main.yaml, examples/jsonknife/bundle/src/01/person.yaml, examples/jsonknife/bundle/src/01/primitive/name.yaml, examples/jsonknife/bundle/src/01/team.yaml
=> Bundle with jsonreference

dictknife/loading/_yaml.py, examples/dictknife/loading/Makefile, examples/dictknife/loading/dst/08output.yaml, examples/dictknife/loading/dst/09output.yaml, examples/dictknife/loading/src/08yaml-string.yaml, examples/dictknife/loading/src/09yaml-string.yaml, examples/jsonknife/bundle/dst/00.yaml, examples/jsonknife/bundle/dst/01.yaml, examples/jsonknife/cut/dst/00.yaml
=> Yaml include hash

dictknife/accessing.py, dictknife/diff/_utils.py, dictknife/diff/diff.py, dictknife/diff/rows.py, dictknife/jsonknife/accessor.py, dictknife/jsonknife/resolver.py, dictknife/swaggerknife/migration.py, dictknife/transform.py, examples/swaggerknife/migrate/00migrate.py, examples/swaggerknife/migrate/2to3.py, examples/swaggerknife/migrate/Makefile, examples/swaggerknife/migrate/dst/00/src/00/main.yaml, examples/swaggerknife/migrate/dst/01/src/2.0.yaml, examples/swaggerknife/migrate/dst/02/src/separated/2.0/api.yaml, examples/swaggerknife/migrate/dst/02/src/separated/2.0/main.yaml, examples/swaggerknife/migrate/dst/03/src/more2.0.yaml, examples/swaggerknife/migrate/src/2.0.yaml, examples/swaggerknife/migrate/src/3.0.yaml, examples/swaggerknife/migrate/src/more2.0.yaml, examples/swaggerknife/migrate/src/more3.0.yaml, examples/swaggerknife/migrate/src/separated/2.0/api.yaml, examples/swaggerknife/migrate/src/separated/2.0/main.yaml
=> tiny first prototype of 2to3 (this is broken)

dictknife/accessing.py
if including list, maybe access return always default. :scream_cat:
=> fix: fix maybe access

dictknife/accessing.py, dictknife/tests/test_accessing_accessor.py
=> fix: fix accessing with list

dictknife/swaggerknife/json2swagger.py, dictknife/swaggerknife/migration.py, examples/swaggerknife/migrate/2to3.py, examples/swaggerknife/migrate/Makefile, examples/swaggerknife/migrate/docker-compose.yml, examples/swaggerknife/migrate/dst/02/bundle.yaml, examples/swaggerknife/migrate/dst/03/more2.0.yaml, examples/swaggerknife/migrate/dst/04/api_users.yaml, examples/swaggerknife/migrate/dst/04/api_users2.yaml, examples/swaggerknife/migrate/dst/04/api_users3.yaml, examples/swaggerknife/migrate/dst/04/bundle.yaml, examples/swaggerknife/migrate/dst/04/components/definitions.yaml, examples/swaggerknife/migrate/dst/04/components/parameters.yaml, examples/swaggerknife/migrate/dst/04/main.yaml, examples/swaggerknife/migrate/src/more3.0.yaml, examples/swaggerknife/migrate/src/separated/more2.0/api_users.yaml, examples/swaggerknife/migrate/src/separated/more2.0/api_users2.yaml, examples/swaggerknife/migrate/src/separated/more2.0/api_users3.yaml, examples/swaggerknife/migrate/src/separated/more2.0/components/definitions.yaml, examples/swaggerknife/migrate/src/separated/more2.0/components/parameters.yaml, examples/swaggerknife/migrate/src/separated/more2.0/main.yaml
=> 2to3 support requestBodies, correctly

dictknife/loading/_gsuite.py
=> fix: add os.expanduser() for cache_path

dictknife/jsonknife/_wrapped_exception.py, dictknife/jsonknife/accessor.py, dictknife/jsonknife/resolver.py, dictknife/tests/jsonknife/test_wrapped_exception.py
=> Wrapped exception

dictknife/loading/_gsuite.py, setup.py
=> Omit oauth2client

dictknife/loading/__init__.py
```
DICTKNIFE_LOAD_FORMAT=json
DICTKNIFE_DUMP_FORMAT=yaml
```
=> feat: loading, use envvar

dictknife/loading/__init__.py
=> fix: fix loading bug

dictknife/commands/dictknife.py, dictknife/commands/jsonknife.py, dictknife/commands/swaggerknife.py
=> With default value, in help message

dictknife/langhelpers.py
=> fix: makedict use std dict()

.gitignore, dictknife/loading/_lazyimport.py, dictknife/tests/cliutils/test_extraarguments.py, examples/dictknife/cat/dst/00person.toml, examples/dictknife/loading/dst/00output.toml, setup.py
use tomlkit
- 📝 tomllib is read only library? https://docs.python.org/3.11/library/tomllib.html
- for #187
=> Omit qtoml

dictknife/commands/dictknife.py, examples/dictknife/diff/Makefile, examples/dictknife/diff/dst/00.pair, examples/dictknife/diff/dst/01.pair
- fix #189 
```console
$ dictknife diff -o pair src/000person.json src/001person.json
{                   {
"name": "foo",      "name": "bar",
"age": 20,          "age": 21,
"type": "person"    "type": "person"
}                   }
```
=> Diff pair view
